First/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
   
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name='food'
urlpatterns = [
    path('', views.IndexClassView.as_view(),name="index"),
    path('bkl/',views.bkl,name="bkl"),
    path('<int:pk>/',views.FoodDetail.as_view(),name="detail"),
    path('add',views.CreateItem.as_view(),name="create_item"),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class item(models.Model):

    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default='https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg')


    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


food/forms.py
from django import forms
from .models import item

class Itemform(forms.ModelForm):
    class Meta:
        model=item
        fields =['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
     email=forms.EmailField()

     class Meta:
          model=User
          fields=['username','email','password1','password2']

food/views.py
from django.forms import BaseModelForm
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import item
from django.template import loader
from .forms import Itemform
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# def index(request):

#     item_list=item.objects.all()
#     context={
#         'item_list':item_list,
#     }
#     return render(request,'food/index.html',context)



class IndexClassView(ListView):
     model=item;
     template_name='food/index.html'
     context_object_name='item_list'
   



def bkl(request):
    return HttpResponse("<h1>teri maa ki choot</h1>")

# def detail(request,item_id):
#         Item=item.objects.get(pk=item_id)
#         context={
#         'item':Item,
#          }
#         return render(request,'food/detail.html',context)



class FoodDetail(DetailView):
     model=item;
     template_name='food/detail.html'
     



# def create_item(request):
#      form = Itemform(request.POST or None)
     
#      if form.is_valid():
#           form.save()
#           return redirect('food:index')
     
#      return render(request,'food/item-form.html',{'form':form})



class CreateItem(CreateView):
     model=item
     fields=['item_name','item_desc','item_price','item_image']
     template_name='food/item-form.html'

     def form_valid(self, form):
          form.instance.user_name=self.request.user

          return super().form_valid(form)






def update_item(request,id):
     
     Item=item.objects.get(id=id)
     form=Itemform(request.POST or None,instance=Item)

     if form.is_valid():
          form.save()
          return redirect('food:index')
     
     return render(request,'food/item-form.html',{'form':form,'item':Item})

   
def delete_item(request,id):
     Item=item.objects.get(id=id)

     if request.method=='POST':
          Item.delete()
          return redirect('food:index')
     
     return render(request,'food/item-delete.html',{'item':Item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
def register(request):
    
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}')
            return redirect('login')
        
    else:
       form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <title>Base</title>
</head>
<body>
      
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Vishal Outlet</a>
    
    <div class="navbar">

      <a class="nav-item navbar-brand bg-light" href="#">View_Item</a>
      <a class="nav-item navbar-brand bg-light " href="{% url 'food:create_item'  %}">Add_item</a>
      <a class="nav-item navbar-brand bg-light" href="#">Delete_Item</a>
      {% if user.is_authenticated %}
         <a href="{% url 'logout' %}">Logout</a>
         <a href="{% url 'profile' %}">profile</a>
      {% else %}
         <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>

</nav>
 {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}}"  >{{ message }}</div>
       
    {% endfor %}
 {% endif %}  

{% block body %}
{% endblock %}


</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="row">
    <div class="col-md-3 offset-md-2">
        <img  class="rounded float-left" height="200px" src="{{item.item_image}}">
    </div>
    <div class="col-md-4">
      <h3>{{object.item_name}}</h3>
      <h4>{{object.item_desc}}</h4>
      <h5>$ {{object.item_price}}</h5>
      <a href="{% url 'food:delete_item' item.id %}">Delete</a>
    </div>
    <div class="col-md-1">
      <a href="{% url 'food:update_item' item.id %}" class="btn btn-success">Update</a>
    </div>
  </div>


{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}


{% block body %}


{% for item in item_list %}

<div class="row">
  <div class="col-md-3 offset-md-2">
      <img  class="rounded float-left" height="140px" src="{{item.item_image}}">
  </div>
  <div class="col-md-4">
    <h3>{{item.item_name}}</h3>
    <h4>{{item.item_desc}}</h4>
    <h5>$ {{item.item_price}}</h5>
    <h6>{{item.user_name}}</h6>
  </div>
  <div class="col-md-2">
    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Detail</a>
  </div>
</div>


{% endfor %}

{% endblock %}

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Sure to delete the element {{ item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html

{% extends 'food/base.html' %}


{% block body %}

<!-- <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form> -->
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add-item
                    </div>
                </div>
                     <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                             {{form}}
                            <button class="bg-info" type="submit">Submit</button>
                        </form>
                       </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
 
{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                       <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                               
                                 <div class="form-group">
                                    {{field.name}}
                                    {{field}}
                                 </div>
                            
                            {% endfor %}
                            <button class="bg-info"  type="submit">Login</button>
                            
                        </form>
                       </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}



users/templates/users/logout.html
<h3>LOGGED OUT</h3>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px"   src="{{ user.profile.image.url}}" >

users/templates/users/register.html
{% extends 'food/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                     <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                               
                            <div class="form-group">
                               {{field.name}}
                               <br>
                               {{field}}
                            </div>
                       
                       {% endfor %}
                            <button class="bg-info" type="submit">SignUp</button>
                        </form>
                       </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}


